[book]
title = "Mental model for unsafe in Rust"
authors = ["Julien Cretin"]
language = "en"
multilingual = false

[output.html]
default-theme = "coal"
git-repository-url = "https://github.com/ia0/unsafe-mental-model"
edit-url-template = "https://github.com/ia0/unsafe-mental-model/edit/main/{path}"

[output.html.playground]
runnable = false
